
// Objective-C API for talking to the following Go packages
//
//	github.com/ktock/container2wasm/iosnet
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Iosnet_FRAMEWORK_H__
#define __Iosnet_FRAMEWORK_H__

#include "Iosnet.objc.h"
#include "Universe.objc.h"

#endif
