#ifndef _RFB_RFBCONFIG_H
#define _RFB_RFBCONFIG_H 1

/* Match the options used by ReDroid's bundled LibVNCServer 0.9.13. */
#define LIBVNCSERVER_HAVE_ANDROID 1
#define LIBVNCSERVER_HAVE_FCNTL_H 1
#define LIBVNCSERVER_HAVE_GETTIMEOFDAY 1
#define LIBVNCSERVER_HAVE_GETHOSTNAME 1
#define LIBVNCSERVER_HAVE_LIBPTHREAD 1
#define LIBVNCSERVER_HAVE_LIBZ 1
#define LIBVNCSERVER_HAVE_NETINET_IN_H 1
#define LIBVNCSERVER_HAVE_SYS_SOCKET_H 1
#define LIBVNCSERVER_HAVE_SYS_STAT_H 1
#define LIBVNCSERVER_HAVE_SYS_TIME_H 1
#define LIBVNCSERVER_HAVE_SYS_TYPES_H 1
#define LIBVNCSERVER_HAVE_SYS_UIO_H 1
#define LIBVNCSERVER_HAVE_UNISTD_H 1
#define LIBVNCSERVER_IPv6 1
#define HAVE_LIBVNCSERVER_PID_T 1
#define HAVE_LIBVNCSERVER_SIZE_T 1
#define HAVE_LIBVNCSERVER_SOCKLEN_T 1
#define LIBVNCSERVER_PACKAGE_STRING "LibVNCServer 0.9.13"
#define LIBVNCSERVER_PACKAGE_VERSION "0.9.13"
#define LIBVNCSERVER_VERSION "0.9.13"

#endif
