// Objective-C API for talking to github.com/ktock/container2wasm/iosnet Go package.
//   gobind -lang=objc github.com/ktock/container2wasm/iosnet
//
// File is generated by gobind. Do not edit.

#ifndef __Iosnet_H__
#define __Iosnet_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


/**
 * Start launches the netstack and serves it over a WebSocket at listenAddr (e.g.
"127.0.0.1:8889"). It blocks serving requests, so call it on a background thread.
Idempotent: a second call while already running returns nil immediately.
The config mirrors cmd/c2w-net (gateway .1, VM .3 via DHCP static lease, NAT to host).
 */
FOUNDATION_EXPORT BOOL IosnetStart(NSString* _Nullable listenAddr, NSError* _Nullable* _Nullable error);

#endif
